// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-credits.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-credits.ts
var get_credits_default = defineTool({
  name: "get_credits",
  title: "Get credit balance",
  description: "Read the signed-in user's AI Tor credit tier, usage and reset time.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_credits").select("paid_tier, used, reset_at, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "No credit record yet \u2014 tier: free, used: 0." }],
        structuredContent: { paid_tier: "free", used: 0 }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { credits: data }
    };
  }
});

// src/lib/mcp/tools/list-uap-sightings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_uap_sightings_default = defineTool2({
  name: "list_uap_sightings",
  title: "List UAP sightings",
  description: "List recent UAP / anomalous aerial sightings tracked by AI Tor, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).nullable().describe("How many sightings to return (default 10)."),
    category: z.string().nullable().describe("Optional category filter, e.g. 'uap' or 'military'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("uap_sightings").select("id, location, lat, lon, type, category, severity, source, source_url, description, date_reported").order("date_reported", { ascending: false }).limit(limit ?? 10);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sightings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-knowledge.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var search_knowledge_default = defineTool3({
  name: "search_knowledge",
  title: "Search AI Tor knowledge base",
  description: "Full-text search over the AI Tor skills/knowledge documents (DAO, physics, Web3, OSINT).",
  inputSchema: {
    query: z2.string().trim().min(2).describe("Search terms."),
    limit: z2.number().int().min(1).max(20).nullable().describe("Max documents to return (default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const term = query.replace(/[%,]/g, " ").trim();
    const { data, error } = await supabase.from("skills_documents").select("id, title, category, source, url, content").or(`title.ilike.%${term}%,content.ilike.%${term}%`).limit(limit ?? 5);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const docs = (data ?? []).map((d) => ({ ...d, content: (d.content ?? "").slice(0, 2e3) }));
    return {
      content: [{ type: "text", text: docs.length ? JSON.stringify(docs) : "No matching documents." }],
      structuredContent: { documents: docs }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wkdtvrxavkhbifjtvvdw";
var mcp_default = defineMcp({
  name: "ai-tor",
  title: "Ai Tor",
  version: "0.1.0",
  instructions: "Tools for AI Tor, the AlienFlow DAO intelligence terminal. Use `search_knowledge` for DAO/physics/Web3 context, `list_uap_sightings` for anomalous aerial events, and `get_credits` for the signed-in user's credit balance.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_credits_default, list_uap_sightings_default, search_knowledge_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
